---
name: CD

on:
  push:
    branches:
      - main
    tags:
      - "*"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  yarn-deploy:
    uses: fire833/cicd-templates/.github/workflows/yarn_deploy_v1.yaml@main
